### ISSUE TITLE
Readouts disappear.

### ISSUE THREAD

**Issue by Nightside101010** [DMagic1/KSP_BasicDeltaV#1]
Hi, I'm really enjoying the latest Basic Delta V, it adds a lot to the game!
I've noticed a bit of a problem though. 
In the editor, with all readouts set to show, things look good when placed, but if I move staging around, some of my readouts, such as TWR stop showing.

If I click on the BasicDeltaV settings panel and click any readout option (such as TWR) off, then back on, everything shows as normal, until I add more parts or change staging order.
![screenshot4](https://user-images.githubusercontent.com/20480557/31728810-2f0e71c2-b3e2-11e7-95f6-be8dc0f5faf4.png)
_Everything working normally._
![screenshot5](https://user-images.githubusercontent.com/20480557/31728817-32870a44-b3e2-11e7-8d12-c6fee0d59d02.png)
_Some readouts don't show._

Everything seems to work as expected in flight mode.

[KSP.log](https://github.com/DMagic1/KSP_BasicDeltaV/files/1395364/KSP.log)

Thanks for your work, @DMagic1 !

Edit: Mods in use are just Module Manager and some MM configs

**Comment by DMagic1** [comment]
Should be fixed in version 2.1.
